export const FIELD_MAPPING: Record<string, string> = {
    // Patio
    'p1': 'patio_servicio',
    'p2': 'basurero_patio',
    'p3': 'zonas_libres_residuos',
    'p4': 'vias_acceso_pavimentas',
    'p5': 'caseta_gas',
    'p6': 'bombona_estado',
    'p7': 'focos_insalubridad',

    // Bodega
    'b1': 'bodega_mp',
    'b2': 'ventilacion_bodega',
    'b3': 'cielos_bodega',
    'b4': 'puertas_bodega',
    'b5': 'ventanas_bodega',
    'b6': 'malla_bodega',
    'b7': 'pisos_bodega',
    'b8': 'paredes_bodega',
    'b9': 'uniones_bodega',
    'b10': 'iluminacion_estado_bodega',
    'b11': 'iluminacion_protegida_bodega',
    'b12': 'iluminacion_adecuada_bodega',
    'b13': 'botiquin',
    'b14': 'extintores',
    'b15': 'conexiones_electricas_bodega',

    // Cocina
    'c1': 'tamano_cocina',
    'c2': 'ventilacion_cocina',
    'c3': 'puertas_cocina',
    'c4': 'ventanas_cocina',
    'c5': 'malla_cocina',
    'c6': 'pisos_cocina',
    'c7': 'paredes_cocina',
    'c8': 'uniones_cocina',
    'c9': 'drenajes',
    'c10': 'inclinacion_pisos',
    'c11': 'cielos_cocina',
    'c12': 'lava_fondos',
    'c13': 'lavamanos_manipulacion',
    'c14': 'dispensador_jabon_papel',
    'c15': 'calefon',
    'c16': 'pre_wash',
    'c17': 'extractor_campana',
    'c18': 'carros_bandejas',
    'c19': 'iluminacion_estado_cocina',
    'c20': 'iluminacion_protegida_cocina',
    'c21': 'iluminacion_adecuada_cocina',
    'c22': 'basureros_tapa_cocina',
    'c23': 'llaves_sifon_cocina',
    'c24': 'canerias_agua',
    'c25': 'canerias_gas',
    'c26': 'conexiones_electricas_cocina',
    'c27': 'trampas_residuos',

    // Baño
    'ba1': 'bano_exclusivo',
    'ba2': 'sin_conexion_directa',
    'ba3': 'puertas_bano',
    'ba4': 'malla_bano',
    'ba5': 'pisos_bano',
    'ba6': 'paredes_bano',
    'ba7': 'lavamanos_caliente_fria',
    'ba8': 'ducha',
    'ba9': 'cortina',
    'ba10': 'dispensadores_jabon_bano',
    'ba11': 'estanque_tapa_wc',
    'ba12': 'espejo',
    'ba13': 'basurero_tapa_bano',
    'ba14': 'llaves_sifon_bano',
    'ba15': 'dispensador_papel',
    'ba16': 'iluminaria_bano',
}

export const PROBLEM_VALUES = [
    'No Cumple',
    'Malo requiere cambio o reparación / No Cumple',
    'No hay y requiere instalar',
    'No'
]
